# Generated by Django 5.1.7 on 2025-03-27 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marvel_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('page_count', models.IntegerField(default=0)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('series', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('detail_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cómic',
                'verbose_name_plural': 'Cómics',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='MarvelCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marvel_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('comics_available', models.IntegerField(default=0)),
                ('series_available', models.IntegerField(default=0)),
                ('stories_available', models.IntegerField(default=0)),
                ('events_available', models.IntegerField(default=0)),
                ('detail_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personaje Marvel',
                'verbose_name_plural': 'Personajes Marvel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CharacterComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='marvel.comic')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to='marvel.marvelcharacter')),
            ],
            options={
                'verbose_name': 'Relación Personaje-Cómic',
                'verbose_name_plural': 'Relaciones Personaje-Cómic',
                'unique_together': {('character', 'comic')},
            },
        ),
    ]
